#!/usr/bin/env bash
# Configure Nginx to have a custom HTTP response header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://www.linkedin.com/in/zakaria-rdouane-190a93242/;
        }

        error_page 404 /404.html;
        location = /404.html{
        internal;
        }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
