#!/usr/bin/env bash
# A script that installs and configures HAProxy on your web servers.

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 282756-web-01 54.210.98.167:80 check
        server 282756-web-02 3.84.255.123:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
