#!/usr/bin/env bash
#This script is displaying fizz buzz and fizzbuzz

i=1

while [ $i -lt 101 ]; do
    if (( i % 15 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo $i
    fi
    (( i++ )) || true
done
