#!/usr/bin/env bash
#This script displays "Best School" 10 times, but on the 9th iteration,
#it displays "Best School" and then "Hi" on a new line.

counter=1

while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi

  ((counter++))
done
